theme = "gruvbox_dark_hard2"

[editor]
line-number = "relative"
mouse = false
completion-trigger-len = 1
cursorline = true
color-modes = true
lsp.display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["spinner", "spacer", "mode", "spacer", "version-control", "file-name", "file-modification-indicator"]
right = ["diagnostics", "workspace-diagnostics", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]

[editor.indent-guides]
render = true
