[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ""]
comment-token = "#"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
auto-format = false
indent = { tab-width = 4, unit = "    " }
config = {}

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 2, unit = "    " }
formatter = { command = "clang-format" }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args=["--parser", "json"] }

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args=["--parser", "html"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args=["--parser", "css"] }

[[language]]
name = "scss"
auto-format = true
formatter = { command = "prettier", args=["--parser", "scss"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args=["--parser", "babel"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args=["--parser", "babel-ts"] }

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args=["--parser", "vue"] }
