[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args=["--parser", "json"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args=["--parser", "json"] }

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args=["--parser", "html"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args=["--parser", "css"] }

[[language]]
name = "scss"
auto-format = true
formatter = { command = "prettier", args=["--parser", "scss"] }

[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" } 